// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.ppdai.framework.raptor.proto;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ppdai.framework.raptor.proto.TestProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string camel_case = 1;</code>
     */
    String getCamelCase();
    /**
     * <code>string camel_case = 1;</code>
     */
    com.google.protobuf.ByteString
        getCamelCaseBytes();

    /**
     * <code>string default_value = 2;</code>
     */
    String getDefaultValue();
    /**
     * <code>string default_value = 2;</code>
     */
    com.google.protobuf.ByteString
        getDefaultValueBytes();
  }
  /**
   * Protobuf type {@code com.ppdai.framework.raptor.proto.TestProto}
   */
  public  static final class TestProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ppdai.framework.raptor.proto.TestProto)
      TestProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestProto.newBuilder() to construct.
    private TestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestProto() {
      camelCase_ = "";
      defaultValue_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              camelCase_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              defaultValue_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Test.internal_static_com_ppdai_framework_raptor_proto_TestProto_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Test.internal_static_com_ppdai_framework_raptor_proto_TestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TestProto.class, Builder.class);
    }

    public static final int CAMEL_CASE_FIELD_NUMBER = 1;
    private volatile Object camelCase_;
    /**
     * <code>string camel_case = 1;</code>
     */
    public String getCamelCase() {
      Object ref = camelCase_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        camelCase_ = s;
        return s;
      }
    }
    /**
     * <code>string camel_case = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCamelCaseBytes() {
      Object ref = camelCase_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        camelCase_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEFAULT_VALUE_FIELD_NUMBER = 2;
    private volatile Object defaultValue_;
    /**
     * <code>string default_value = 2;</code>
     */
    public String getDefaultValue() {
      Object ref = defaultValue_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        defaultValue_ = s;
        return s;
      }
    }
    /**
     * <code>string default_value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDefaultValueBytes() {
      Object ref = defaultValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        defaultValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCamelCaseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, camelCase_);
      }
      if (!getDefaultValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, defaultValue_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCamelCaseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, camelCase_);
      }
      if (!getDefaultValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, defaultValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TestProto)) {
        return super.equals(obj);
      }
      TestProto other = (TestProto) obj;

      boolean result = true;
      result = result && getCamelCase()
          .equals(other.getCamelCase());
      result = result && getDefaultValue()
          .equals(other.getDefaultValue());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CAMEL_CASE_FIELD_NUMBER;
      hash = (53 * hash) + getCamelCase().hashCode();
      hash = (37 * hash) + DEFAULT_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getDefaultValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TestProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TestProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ppdai.framework.raptor.proto.TestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ppdai.framework.raptor.proto.TestProto)
        TestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Test.internal_static_com_ppdai_framework_raptor_proto_TestProto_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Test.internal_static_com_ppdai_framework_raptor_proto_TestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TestProto.class, Builder.class);
      }

      // Construct using com.ppdai.framework.raptor.proto.Test.TestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        camelCase_ = "";

        defaultValue_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Test.internal_static_com_ppdai_framework_raptor_proto_TestProto_descriptor;
      }

      public TestProto getDefaultInstanceForType() {
        return TestProto.getDefaultInstance();
      }

      public TestProto build() {
        TestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public TestProto buildPartial() {
        TestProto result = new TestProto(this);
        result.camelCase_ = camelCase_;
        result.defaultValue_ = defaultValue_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TestProto) {
          return mergeFrom((TestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TestProto other) {
        if (other == TestProto.getDefaultInstance()) return this;
        if (!other.getCamelCase().isEmpty()) {
          camelCase_ = other.camelCase_;
          onChanged();
        }
        if (!other.getDefaultValue().isEmpty()) {
          defaultValue_ = other.defaultValue_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TestProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object camelCase_ = "";
      /**
       * <code>string camel_case = 1;</code>
       */
      public String getCamelCase() {
        Object ref = camelCase_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          camelCase_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string camel_case = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCamelCaseBytes() {
        Object ref = camelCase_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          camelCase_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string camel_case = 1;</code>
       */
      public Builder setCamelCase(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        camelCase_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string camel_case = 1;</code>
       */
      public Builder clearCamelCase() {

        camelCase_ = getDefaultInstance().getCamelCase();
        onChanged();
        return this;
      }
      /**
       * <code>string camel_case = 1;</code>
       */
      public Builder setCamelCaseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        camelCase_ = value;
        onChanged();
        return this;
      }

      private Object defaultValue_ = "";
      /**
       * <code>string default_value = 2;</code>
       */
      public String getDefaultValue() {
        Object ref = defaultValue_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          defaultValue_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string default_value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDefaultValueBytes() {
        Object ref = defaultValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          defaultValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string default_value = 2;</code>
       */
      public Builder setDefaultValue(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        defaultValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string default_value = 2;</code>
       */
      public Builder clearDefaultValue() {

        defaultValue_ = getDefaultInstance().getDefaultValue();
        onChanged();
        return this;
      }
      /**
       * <code>string default_value = 2;</code>
       */
      public Builder setDefaultValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        defaultValue_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ppdai.framework.raptor.proto.TestProto)
    }

    // @@protoc_insertion_point(class_scope:com.ppdai.framework.raptor.proto.TestProto)
    private static final TestProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TestProto();
    }

    public static TestProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestProto>
        PARSER = new com.google.protobuf.AbstractParser<TestProto>() {
      public TestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TestProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestProto> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TestProto> getParserForType() {
      return PARSER;
    }

    public TestProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ppdai_framework_raptor_proto_TestProto_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ppdai_framework_raptor_proto_TestProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ntest.proto\022 com.ppdai.framework.raptor" +
      ".proto\"6\n\tTestProto\022\022\n\ncamel_case\030\001 \001(\t\022" +
      "\025\n\rdefault_value\030\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ppdai_framework_raptor_proto_TestProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ppdai_framework_raptor_proto_TestProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ppdai_framework_raptor_proto_TestProto_descriptor,
        new String[] { "CamelCase", "DefaultValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
